"""Distractor policies — realistic rules a brand accumulates that are simply
not relevant to any query in the benchmark.

Purpose: grow the policy list from 25 to 100 without inventing new gold labels.
Every distractor must be false for all 47 queries, so any distractor the model
fires is a false positive and nothing else. Conditions were written to avoid
every topic the labelled query set touches, then screened empirically by
screen_distractors.py; anything that fired on a real query was removed.
"""

DISTRACTORS = [
    ("d_contact_lenses", "filter", "The user asks about contact lenses or contact lens solution."),
    ("d_reading_strength", "filter", "The user names a reading-glasses dioptre strength such as +1.50."),
    ("d_progressive", "filter", "The user asks about progressive, varifocal or bifocal lenses."),
    ("d_ar_coating", "boost", "The user asks about anti-reflective or anti-glare lens coating."),
    ("d_photochromic", "boost", "The user asks about photochromic or transition lenses that darken in sunlight."),
    ("d_mirrored", "boost", "The user asks for a mirrored or reflective lens finish."),
    ("d_titanium", "response", "The user asks how titanium frames compare with acetate frames."),
    ("d_rimless", "filter", "The user asks for rimless or semi-rimless frames."),
    ("d_clip_on", "pin", "The user asks about clip-on lens attachments."),
    ("d_swim_goggles", "filter", "The user asks about swimming goggles."),
    ("d_safety_glasses", "filter", "The user asks about safety glasses for workshop, welding or industrial use."),
    ("d_motorcycle", "boost", "The user mentions motorcycling or riding a motorbike."),
    ("d_aviation", "boost", "The user mentions flying an aircraft or being a pilot."),
    ("d_fishing", "boost", "The user mentions fishing or boating."),
    ("d_golf", "boost", "The user mentions golf."),
    ("d_tennis", "boost", "The user mentions tennis or racquet sports."),
    ("d_vr_inserts", "response", "The user asks about prescription lens inserts for a VR headset."),
    ("d_pet_eyewear", "response", "The user asks about eyewear for a dog or other pet."),
    ("d_tint_category", "response", "The user asks about lens tint categories or tint percentage."),
    ("d_corporate_bulk", "response", "The user asks about a corporate, bulk or wholesale order."),
    ("d_insurance_fsa", "response", "The user asks about vision insurance, FSA or HSA reimbursement."),
    ("d_financing", "response", "The user asks about instalment payments, financing or buy-now-pay-later."),
    ("d_trade_in", "response", "The user asks about trading in or recycling an old pair of frames."),
    ("d_subscription", "response", "The user asks about a subscription or auto-replenishment plan."),
    ("d_black_friday", "boost", "The user asks specifically about Black Friday or Cyber Monday."),
    ("d_lunar_new_year", "pin", "The user mentions Diwali, Lunar New Year or Ramadan."),
    ("d_student_discount", "response", "The user says they are a student or asks about a student discount."),
    ("d_military_discount", "response", "The user says they are military, a veteran, or a first responder."),
    ("d_international_ship", "response", "The user asks about shipping outside the United States."),
    ("d_express_ship", "response", "The user asks specifically about overnight, express or next-day delivery."),
    ("d_gift_card", "response", "The user asks about gift cards or e-gift vouchers."),
    ("d_lost_package", "response", "The user says a package was lost, stolen or arrived damaged."),
    ("d_order_tracking", "response", "The user asks where an existing order is or for a tracking number."),
    ("d_cancel_order", "response", "The user asks to cancel an order they already placed."),
    ("d_change_address", "response", "The user asks to change the delivery address on an existing order."),
    ("d_account_login", "response", "The user cannot log in or asks to reset their password."),
    ("d_newsletter", "response", "The user asks to subscribe to or unsubscribe from marketing email."),
    ("d_privacy_request", "response", "The user asks to delete their personal data or asks about privacy policy."),
    ("d_lens_replacement", "response", "The user asks to have new lenses fitted into frames they already own."),
    ("d_price_match", "response", "The user asks whether you will price match another retailer."),
    ("d_authenticity", "response", "The user asks how to verify that a product is authentic and not counterfeit."),
    ("d_sustainability", "response", "The user asks about recycled materials or the brand's environmental footprint."),
    ("d_vegan_materials", "response", "The user asks whether materials are vegan or cruelty-free."),
    ("d_country_origin", "response", "The user asks in which country the frames are manufactured."),
    ("d_charity", "response", "The user asks about the brand's charitable or donation programme."),
    ("d_optometrist_b2b", "response", "The user identifies as an optometrist or optical retailer seeking a partnership."),
    ("d_press_enquiry", "response", "The user identifies as a journalist or asks for a press contact."),
    ("d_careers", "response", "The user asks about job openings or careers at the company."),
    ("d_affiliate", "response", "The user asks about an affiliate, ambassador or influencer programme."),
    ("d_app_download", "response", "The user asks about a mobile app or where to download it."),
    ("d_lens_scratch_kit", "response", "The user asks about a scratch-repair kit for lenses."),
    ("d_frame_colour_custom", "pin", "The user asks whether frames can be custom painted or engraved."),
    ("d_left_handed", "response", "The user mentions being left-handed."),
    ("d_altitude", "boost", "The user mentions mountaineering above 3,000 metres or glacier travel."),
    ("d_desert_dust", "boost", "The user mentions desert, sandstorm or dust protection."),
    ("d_night_shift", "response", "The user says they work night shifts."),
    ("d_colour_blind", "filter", "The user says they are colour blind or asks about colour-correcting lenses."),
    ("d_dry_climate", "response", "The user asks about eyewear for very dry or very humid climates."),
    ("d_helmet_compat", "response", "The user asks whether frames fit under a helmet."),
    ("d_hearing_aid", "response", "The user mentions wearing hearing aids alongside glasses."),
    ("d_cpap", "response", "The user mentions using a CPAP mask."),
    ("d_school_uniform", "response", "The user asks about a school uniform policy on eyewear."),
    ("d_sports_team", "response", "The user asks about team or club bulk branding on frames."),
    ("d_photography", "response", "The user mentions photography or camera viewfinders."),
    ("d_stargazing", "boost", "The user mentions astronomy or stargazing."),
    ("d_theatre_opera", "response", "The user asks about opera glasses or binoculars."),
    ("d_magnifier", "response", "The user asks about handheld magnifiers."),
    ("d_eyewear_chains", "response", "The user asks about eyewear chains, cords or lanyards."),
    ("d_nose_pad_replace", "response", "The user asks to buy replacement nose pads or temple tips."),
    ("d_screw_kit", "response", "The user asks about a repair screw kit or a small screwdriver."),
    ("d_travel_insurance", "response", "The user asks about insuring eyewear while travelling."),
    ("d_duty_free", "response", "The user asks about duty-free or airport collection."),
    ("d_currency", "response", "The user asks to see prices in a currency other than US dollars."),
    ("d_tax_exempt", "response", "The user asks about sales-tax exemption or a resale certificate."),
    ("d_wedding", "pin", "The user mentions a wedding or being part of a bridal party."),
]

DISTRACTOR_IDS = [d[0] for d in DISTRACTORS]
